title: HamaP의 블로그
description: 해킹과 보안, 클라우드 공부 기록
author: HamaP
baseurl: ""
url: "https://hamap0.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

collections:
  posts:
    output: true

future: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      primary_category: "uncategorized"

# Settings for jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category_page
  permalinks:
    category: '/category/:name/'